import type { Config } from '@netlify/functions';

export default async (): Promise<Response> => {
  return new Response(
    'Hello, world! This message was generated by a Netlify function.'
  );
};

export const config: Config = {
  path: '/hello-world'
};
