import type { Config } from "@netlify/functions"

export default async () => {
  return new Response("This message was generated by a Netlify function.")
}

export const config: Config = {
  path: "/hello-world"
};
