import type { Config, Context } from "@netlify/functions"

export default async (req: Request, context: Context) => {
  return new Response("This message was generated by a Netlify function.")
}

export const config: Config = {
  path: "/hello-world"
};
